language: ruby
rvm:
  - "2.1.10"
  - "2.2.10"
  - "2.3.7"
  - "2.4.4"
  - "2.5.1"
cache: bundler
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/activesupport5.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/activesupport5.gemfile
gemfile:
  - gemfiles/activesupport5.gemfile
  - gemfiles/activesupport4.gemfile
