language: ruby
rvm:
  - "2.3.8"
  - "2.4.4"
  - "2.4.5"
  - "2.5.3"
  - "2.6.1"
cache: bundler
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

matrix:
  exclude:
gemfile:
  - gemfiles/activesupport5.gemfile
  - gemfiles/activesupport4.gemfile
